services:
  dbt-core:
    build:
      context: .
      dockerfile: Dockerfile
      target: dbt-core
      args:
        build_for: linux/amd64
        dbt_core_ref: dbt-core@v1.7.0
    working_dir: /usr/app/dbt/
    entrypoint: ["dbt"]
    volumes:
      - ./:/usr/app/dbt
    networks:
      - default

  dbt-clickhouse:
    build:
      context: .
      dockerfile: Dockerfile
      target: dbt-clickhouse
      args:
        build_for: linux/amd64
    working_dir: /usr/app/dbt/
    entrypoint: ["dbt"]
    volumes:
      - ./:/usr/app/dbt
    networks:
      - default


networks:
  default:
    name: ${LOCAL_NETWORK}
    external: true
