services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"    # API порт
      - "9001:9001"    # Web-консоль
    env_file: .env
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - default

volumes:
  minio_data:
  minio_config:

networks:
  default:
    name: ${LOCAL_NETWORK}
    external: true