services:
  postgres:
    image: postgres:13.21-alpine3.21
    container_name: postgres
    environment:
      POSTGRES_USER: admin              # Логин (можно оставить 'postgres')
      POSTGRES_PASSWORD: admin     # Пароль (замените!)
      POSTGRES_DB: default_db          # Создаваемая БД при старте
      PGDATA: /var/lib/postgresql/data/pgdata  # Путь к данным внутри контейнера
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Постоянное хранилище данных
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf  # Кастомный конфиг
    command: postgres -c config_file=/etc/postgresql/postgresql.conf  # Загрузка конфига
    restart: unless-stopped
    networks:
      - default

  # PGAdmin для визуального управления
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Почта для PGAdmin
      PGADMIN_DEFAULT_PASSWORD: admin        # Пароль для PGAdmin
    ports:
      - "5050:80"  # Доступ через http://localhost:5050
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Сохранение сессий PGAdmin
    networks:
      - default
    restart: unless-stopped


networks:
  default:
    name: ${LOCAL_NETWORK}
    external: true