services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: admin              # Логин (можно оставить 'postgres')
      POSTGRES_PASSWORD: admin          # Пароль (замените!)
      POSTGRES_DB: postgres             # Создаваемая БД при старте
      PGDATA: /var/lib/postgresql/data/pgdata  # Путь к данным внутри контейнера
    ports:
      - "5435:5432"  # Явно указываем внешний порт 5435
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
    command: >
      postgres -c config_file=/etc/postgresql/postgresql.conf
      -c listen_addresses='*'
      -c port=5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d app_db -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - default

  # PGAdmin для визуального управления
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Почта для PGAdmin
      PGADMIN_DEFAULT_PASSWORD: admin        # Пароль для PGAdmin
    ports:
      - "5050:80"  # Доступ через http://localhost:5050
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Сохранение сессий PGAdmin
    networks:
      - default
    restart: unless-stopped

# Объявление сетей и volumes
volumes:
  postgres_data:  # Том для данных PostgreSQL
  pgadmin_data:   # Том для данных PGAdmin

networks:
  default:
    name: ${LOCAL_NETWORK}
    external: true